#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$((
  find ~/Nextcloud/work -maxdepth 2 -type d;
  find ~/Nextcloud/personal -maxdepth 2 -type d; 
  find ~/Nextcloud/Uni -maxdepth 2 -type d; 
  find ~/Nextcloud/Uni/6.Semester -maxdepth 3 -type d;
  find ~/Nextcloud/Uni/7.Semester -maxdepth 3 -type d;
  ) | fzf)
fi

if [[ -z $selected ]]; then
	exit 0
fi

echo $selected
